### ISSUE TITLE
Exception on update after long wait

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#14]
Steps taken:

- update wurst setup app to latest on wurstlang.org
- have out-of-date compiler (build 610, upgrading to 797)
- "update wurst" in the wurst setup app

```
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-55
java.security.PrivilegedActionException: java.io.FileNotFoundException: wurstpack_compiler.zip (The system cannot find the file specified)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: wurstpack_compiler.zip (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at file.ZipArchiveExtractor.extractArchive(ZipArchiveExtractor.kt:27)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:103)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:19)
	at workers.DownloadWithProgressWorker.done(DownloadWithProgressWorker.kt:56)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	... 9 more
```

**Comment by Frotty** [comment]
`PrivilegedActionException` looks like you're blocking the downloaded file

**Comment by Cokemonkey11** [comment]
My best guess then is that the file already exists. Where is it trying to download to?

**Comment by Cokemonkey11** [comment]
After the latest update I still hit

```
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-59
java.security.PrivilegedActionException: java.io.FileNotFoundException: wurstpack_compiler.zip (The system cannot find the file specified)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: wurstpack_compiler.zip (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at file.ZipArchiveExtractor.extractArchive(ZipArchiveExtractor.kt:27)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:105)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:19)
	at workers.DownloadWithProgressWorker.done(DownloadWithProgressWorker.kt:56)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	... 9 more

```

**Comment by Frotty** [comment]
I didn't push anything regarding your problem, as you havn't provided any meaningful steps to reproduce the issue.

**Comment by Cokemonkey11** [comment]
> My best guess then is that the file already exists. Where is it trying to download to?

Where should I expect wurstpack_compiler.zip to be? Maybe I can inspect that directory's contents.

Also where can I find a full backtrace?

And I checked AppData for logs but don't see Wurst there anymore - has that been moved?

**Comment by Cokemonkey11** [comment]
I found this:

```
2018-06-11 19:14:17 [main] INFO  file.SetupApp - is GUI launch 
2018-06-11 19:14:17 [main] INFO  file.SetupApp - startup setup version: <1.1.4.0-jenkins-WurstSetup-59> 
2018-06-11 19:14:17 [main] INFO  global.InstallationManager - verify Install 
2018-06-11 19:14:17 [main] INFO  file.SetupApp - path: file:/C:/Users/Blake/Desktop/desktop/WurstSetup.jar 
2018-06-11 19:14:17 [main] INFO  file.SetupApp - file: C:\Users\Blake\Desktop\desktop\WurstSetup.jar 
2018-06-11 19:14:17 [main] INFO  file.SetupApp - copy jar 
2018-06-11 19:14:17 [AWT-EventQueue-0] INFO  ui.MainWindow - init UI 
2018-06-11 19:14:18 [SwingWorker-pool-2-thread-2] INFO  net.ConnectionManager - couldn't contact wurst jenkins: Stream closed 
2018-06-11 19:14:19 [SwingWorker-pool-2-thread-2] INFO  global.InstallationManager - verify Install 
2018-06-11 19:14:22 [AWT-EventQueue-0] INFO  ui.MainWindow - handle wurst update 
2018-06-11 19:14:22 [SwingWorker-pool-2-thread-3] INFO  global.InstallationManager - isUpdate 
2018-06-11 19:14:22 [SwingWorker-pool-2-thread-3] INFO  global.InstallationManager - download compiler 
2018-06-11 19:14:22 [SwingWorker-pool-2-thread-4] ERROR workers.DownloadWithProgressWorker - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
2018-06-11 19:14:22 [AWT-EventQueue-0] INFO  global.InstallationManager - extract compiler 

```

**Comment by Frotty** [comment]
java version?

**Comment by Cokemonkey11** [comment]
Environment variables are configured with `C:\Program Files\Java\jdk1.8.0_31`

**Comment by Frotty** [comment]
https://wurstlang.org/start.html
> Make sure your minor version 1.8.0_xxx (xxx) is higher than 101 to avoid any certificate issues.

**Comment by Cokemonkey11** [comment]
That's fixed it, thanks!

**Comment by Frotty** [comment]
Okay, still, the setup should just use http when https fails. 
But I think the `ValidatorException` is not an IOException and thus not caught by the try.
Pushed some fixes.

**Comment by Cokemonkey11** [comment]
Cool. I guess an alternative to trying without SSL is to leave a nice warning "Couldn't download with SSL - is your JDK version at least xxx?"
