### ISSUE TITLE
ERROR Could not open/create prefs root node Software\JavaSoft\Prefs

### ISSUE THREAD

**Issue by Meai1** [wurstscript/WurstSetup#22]
```
C:\Users\pc\Downloads>java -jar WurstSetup.jar
2018-10-17 11:15:18 [main] INFO  file.SetupApp - is GUI launch
2018-10-17 11:15:18 [main] INFO  file.SetupApp - startup setup version: <1.1.5.0-jenkins-WurstSetup-72>
2018-10-17 11:15:18 [main] INFO  global.InstallationManager - verify Install
2018-10-17 11:15:18 [main] INFO  file.SetupApp - path: file:/C:/Users/pc/Downloads/WurstSetup.jar
2018-10-17 11:15:18 [main] INFO  file.SetupApp - file: C:\Users\pc\Downloads\WurstSetup.jar
2018-10-17 11:15:18 [main] INFO  file.SetupApp - copy jar
2018-10-17 11:15:19 [AWT-EventQueue-0] INFO  ui.MainWindow - init UI
Okt. 17, 2018 11:15:20 VORM. java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by global.WinRegistry (file:/C:/Users/pc/Downloads/WurstSetup.jar) to method java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int,byte[],int)
WARNING: Please consider reporting this to the maintainers of global.WinRegistry
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
        at ui.UiManager$initUI$1.run(UiManager.kt:15)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
```

No, I DONT want to run it with admin rights.
java 10.0.2 2018-07-17

**Comment by Frotty** [comment]
Java 9 and up are not supported yet.

**Comment by Frotty** [comment]
nvm, it works on other machines with java 9+

> No, I DONT want to run it with admin rights.

And why?
It would verify if the problem is caused by missing permissions.
The setup only **reads** your wc3 game path.

**Comment by Meai1** [comment]
yeah I realized that it launches fine afterwards, btw on win10 maybe the registry is different

**Comment by Frotty** [comment]
No, it was code left behind which didn't throw warnings on java 8, but do now.
I will push a big update to setup soon which will address both of them.
Thanks again 😃
