### ISSUE TITLE
ExceptionInInitiallizerError when starting up .jar

### ISSUE THREAD

**Issue by Kipx** [wurstscript/WurstSetup#24]
Please report this crash with the following info:
Version: 1.1.5.0-jenkins-WurstSetup-82
java.lang.ExceptionInInitializerError
	at ui.MainWindow$UI.createConfigTable(MainWindow.kt:315)
	at ui.MainWindow$UI.initComponents(MainWindow.kt:150)
	at ui.MainWindow.init(MainWindow.kt:68)
	at ui.UiManager$initUI$1.run(UiManager.kt:13)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at global.WinRegistry.<clinit>(WinRegistry.kt:51)
	... 17 more
Caused by: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at global.WinRegistry.<clinit>(WinRegistry.kt:30)
	... 17 more

Currently running Java 1.8.0_191

**Comment by Frotty** [comment]
Are you sure you're running Java 8? Only encountered this on 9+ so far.
Are you on linux? Try running from command line and see if that works.

**Comment by Kipx** [comment]
Uninstalled JRE and JDK and it works perfectly now. Was probably using one of those (a couple of my setups previously had the JAVA_HOME set to something erroneous; i had forgotten)

Sorry for the trouble!
