### ISSUE TITLE
WurstSetup Crash on First Use

### ISSUE THREAD

**Issue by DaffaMage** [wurstscript/WurstSetup#29]
```
Please report this crash with the following info:
Version: 1.1.5.0-jenkins-WurstSetup-85
java.lang.ExceptionInInitializerError
	at ui.MainWindow$UI.createConfigTable(MainWindow.kt:315)
	at ui.MainWindow$UI.initComponents(MainWindow.kt:150)
	at ui.MainWindow.init(MainWindow.kt:68)
	at ui.UiManager$initUI$1.run(UiManager.kt:13)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at global.WinRegistry.<clinit>(WinRegistry.kt:51)
	... 17 more
Caused by: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at global.WinRegistry.<clinit>(WinRegistry.kt:30)
	... 17 more
```

Tried in Downloads and Documents folders and still get this error. Uninstalled an old one since it's crashing with a different error as well. Java 1.8.0_172.

**Comment by Frotty** [comment]
There are some issues with the old WinRegistry implementation with newer java versions/systems.
It's addressed by #26 which I will hopefully merge this weekend.

**Comment by MaxSvargal** [comment]
The same problem, but another message:
```Please report this crash with the following info:
Version: 1.1.5.0-jenkins-WurstSetup-91
java.lang.IllegalStateException: key.getValueByName("InstallPath") must not be null
	at ui.MainWindow$UI.createConfigTable(MainWindow.kt:312)
	at ui.MainWindow$UI.initComponents(MainWindow.kt:153)
	at ui.MainWindow.init(MainWindow.kt:70)
	at ui.UiManager$initUI$1.run(UiManager.kt:12)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)```

**Comment by Frotty** [comment]
Should be fixed, but I still wonder why you don't have registry entries. Did you not install wc3 conventionally?

**Comment by MaxSvargal** [comment]
> Should be fixed, but I still wonder why you don't have registry entries. Did you not install wc3 conventionally?
At now it's ok. Of course wc3 installed correctly.
