### ISSUE TITLE
WurstSetup Exception

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstSetup#3]
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-50
us.monoid.json.JSONException: JSONObject["buildsByBranchName"] not found.
	at us.monoid.json.JSONObject.get(JSONObject.java:419)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:74)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.JSONPathQuery.eval(JSONPathQuery.java:42)
	at us.monoid.web.JSONResource.get(JSONResource.java:130)
	at net.ConnectionManager.getJson(ConnectionManager.kt:24)
	at net.ConnectionManager.getBuildNumber(ConnectionManager.kt:64)
	at net.ConnectionManager.getLatestCompilerBuild(ConnectionManager.kt:79)
	at global.InstallationManager.verifyInstallation(InstallationManager.kt:50)
	at file.SetupApp.startup(SetupApp.kt:86)
	at file.SetupApp.handleArgs(SetupApp.kt:22)
	at file.SetupMain.doMain(SetupMain.kt:54)
	at file.SetupMain$Companion.main(SetupMain.kt:61)
	at file.SetupMain.main(SetupMain.kt)

**Comment by Frotty** [comment]
please post the log and what you did to make this occur

**Comment by DDLegionTN** [comment]
The day that you've fixed the setup issue, was working fine. Then a few days I didn't touch WurstSetup until today, and it ends up with such error. Restarted PC doesn't fix as well.

Log :
> 2018-02-06 20:49:12 [main] INFO  file.SetupApp - startup setup version: <1.1.4.0-jenkins-WurstSetup-50> 
> 2018-02-06 20:49:15 [main] INFO  file.SetupApp - ConnectionStatus: ONLINE 
> 2018-02-06 20:49:15 [main] INFO  global.InstallationManager - verify Install 
> 2018-02-06 20:49:18 [main] WARN  global.InstallationManager - Installation is custom.

**Comment by Frotty** [comment]
did you mess with your installation? it says "custom". 
You can try deleting the .wurst folder in your user folder and reinstall. Can't look at this issue right now.

**Comment by texel-sensei** [comment]
The problem occurs for me when I start the setup for the first time, never had wurst on this pc before.
The logfile just contains this:
```
2018-02-06 19:27:54 [main] INFO  file.SetupApp - startup setup version: <1.1.4.0-jenkins-WurstSetup-50> 
2018-02-06 19:27:55 [main] INFO  file.SetupApp - ConnectionStatus: ONLINE 
2018-02-06 19:27:55 [main] INFO  global.InstallationManager - verify Install 

```

**Comment by Frotty** [comment]
Okay, for some reason the json api of our buildserver changed. 
I have made the check now more robust and also prevent exceptions from happening for this kind of error.
Thanks for reporting.
