### ISSUE TITLE
Malformed string in wurst.build crashes WurstSetup

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#39]
# Symptoms:

- Error trace and crash:

```
Please report this crash with the following info:
Version: 1.2.1.0-jenkins-WurstSetup-121
file.YamlHelper$YamlException: wurst.build file could not be read. Input malformed or corrupt.
	at file.YamlHelper.loadProjectConfig(YamlHelper.kt:38)
	at config.WurstProjectConfig.loadProject(WurstProjectConfig.kt:38)
	at ui.MainWindow$UI.handleImport(MainWindow.kt:377)
	at ui.MainWindow$UI.access$handleImport(MainWindow.kt:99)
	at ui.MainWindow$UI$createButtonTable$3.mouseClicked(MainWindow.kt:509)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

- You have a string in your `wurst.build` that's malformed, for example:

```
buildMapData:
  name: 'My mate's map'
```

# Expected Behaviour

The error should be mapped/pretty-printed to the user

# Workaround

Don't write bad yaml

**Comment by Frotty** [comment]
I consider this fixed since we now ship the YAML plugin, which provides some validation.
![](https://i.imgur.com/hkiIyAc.png)
