### ISSUE TITLE
Setup Crashes when in root folder of HDD

### ISSUE THREAD

**Issue by texel-sensei** [wurstscript/WurstSetup#4]
When I start WurstSetup.jar in the root folder of a drive (`T:\WurstSetup.jar`) then it crashes with the following error:
```
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-51
java.lang.NullPointerException
	at file.SetupApp.copyJar(SetupApp.kt:95)
	at file.SetupApp.startup(SetupApp.kt:87)
	at file.SetupApp.handleArgs(SetupApp.kt:22)
	at file.SetupMain.doMain(SetupMain.kt:54)
	at file.SetupMain$Companion.main(SetupMain.kt:61)
	at file.SetupMain.main(SetupMain.kt)
```
Log contains the following:
```
2018-02-07 19:36:07 [main] INFO  file.SetupApp - startup setup version: <1.1.4.0-jenkins-WurstSetup-51> 
2018-02-07 19:36:07 [main] INFO  file.SetupApp - ConnectionStatus: ONLINE 
2018-02-07 19:36:07 [main] INFO  global.InstallationManager - verify Install 
2018-02-07 19:36:08 [main] INFO  file.SetupApp - path: file:/T:/WurstSetup.jar 
2018-02-07 19:36:08 [main] INFO  file.SetupApp - file: T:\WurstSetup.jar 
```

When I copy the jar file into a subfolder (`T:\foo\WurstSetup.jar`) then it works as expected.

**Comment by Frotty** [comment]
Thanks for the report 👍
