### ISSUE TITLE
`grill install` drops RefAlreadyExistsException for each ref

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#40]
```
blake@LAPTOP-ASBN7T4S:~/workspace/the-gorge$ grill install                                                                                                                                                                           [1108/1752]
🔥 Grill warming up..
🔥 Ready. Version: <1.3.1.1-jenkins-WurstSetup-123>
🔷 Installing dependencies..
        🔹 Pulling <WurstStdlib2:master>
org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
        at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:129)
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:225)
        at file.DependencyManager.prepareRepo(DependencyManager.kt:163)
        at file.DependencyManager.cleanRepo(DependencyManager.kt:145)
        at file.DependencyManager.updateDependencies(DependencyManager.kt:37)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:168)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:218)
        at file.SetupApp.handleRunArgs(SetupApp.kt:64)
        at file.SetupApp.handleCMD(SetupApp.kt:44)
        at file.SetupApp.handleArgs(SetupApp.kt:35)
        at file.SetupMain.doMain(SetupMain.kt:38)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)
        🔹 Pulling <WurstCommand:master>
org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
        at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:129)
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:225)
        at file.DependencyManager.prepareRepo(DependencyManager.kt:163)
        at file.DependencyManager.cleanRepo(DependencyManager.kt:145)
        at file.DependencyManager.updateDependencies(DependencyManager.kt:37)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:168)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:218)
        at file.SetupApp.handleRunArgs(SetupApp.kt:64)
        at file.SetupApp.handleCMD(SetupApp.kt:44)
        at file.SetupApp.handleArgs(SetupApp.kt:35)
        at file.SetupMain.doMain(SetupMain.kt:38)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)
        🔹 Pulling <WurstLinkedHashMap:master>
org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
        at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:129)
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:225)
        at file.DependencyManager.prepareRepo(DependencyManager.kt:163)
        at file.DependencyManager.cleanRepo(DependencyManager.kt:145)
        at file.DependencyManager.updateDependencies(DependencyManager.kt:37)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:168)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:218)
        at file.SetupApp.handleRunArgs(SetupApp.kt:64)
        at file.SetupApp.handleCMD(SetupApp.kt:44)
        at file.SetupApp.handleArgs(SetupApp.kt:35)
        at file.SetupMain.doMain(SetupMain.kt:38)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)
        🔹 Pulling <WurstRealHeapGuard:master>
org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
        at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:129)
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:225)
        at file.DependencyManager.prepareRepo(DependencyManager.kt:163)
        at file.DependencyManager.cleanRepo(DependencyManager.kt:145)
        at file.DependencyManager.updateDependencies(DependencyManager.kt:37)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:168)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:218)
        at file.SetupApp.handleRunArgs(SetupApp.kt:64)
        at file.SetupApp.handleCMD(SetupApp.kt:44)
        at file.SetupApp.handleArgs(SetupApp.kt:35)
        at file.SetupMain.doMain(SetupMain.kt:38)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)
        🔹 Pulling <wurst-lodash:master>
org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
        at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:129)
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:225)
        at file.DependencyManager.prepareRepo(DependencyManager.kt:163)
        at file.DependencyManager.cleanRepo(DependencyManager.kt:145)
        at file.DependencyManager.updateDependencies(DependencyManager.kt:37)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:168)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:218)
        at file.SetupApp.handleRunArgs(SetupApp.kt:64)
        at file.SetupApp.handleCMD(SetupApp.kt:44)
        at file.SetupApp.handleArgs(SetupApp.kt:35)
        at file.SetupMain.doMain(SetupMain.kt:38)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)
✔ Installed dependencies!
```

**Comment by Frotty** [comment]
What did you input? Just log is useless.

**Comment by Cokemonkey11** [comment]
```
blake@LAPTOP-ASBN7T4S:~/workspace/the-gorge$ cat wurst.build
---
projectName: Battle Planes
dependencies:
- https://github.com/wurstscript/WurstStdlib2
- https://github.com/Cokemonkey11/WurstCommand
- https://github.com/Cokemonkey11/WurstLinkedHashMap
- https://github.com/Cokemonkey11/WurstRealHeapGuard
- https://github.com/theQuazz/wurst-lodash
buildMapData:
  name: '|cff999999Battle Planes|r 0.14.5'
  fileName: (10)BattlePlanes0.14.5
  author: Cokemonkey11
```

**Comment by Frotty** [comment]
Ah okay, it's just a `e.printStackTrace()` and everything is working fine.

**Comment by Cokemonkey11** [comment]
Thanks! LGTM
