### ISSUE TITLE
`grill --help` drops IllegalArgumentException

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#42]
```
blake@LAPTOP-ASBN7T4S:~/workspace$ grill --help
🔥 Invalid grill command <--help> ! Available commands: [generate|install|remove|test|build] <command argument>
java.lang.IllegalArgumentException: No enum constant file.CLICommand.--HELP
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at file.CLICommand.valueOf(CLICommand.kt)
        at file.SetupMain.parseCLIArgs(SetupMain.kt:45)
        at file.SetupMain.doMain(SetupMain.kt:36)
        at file.SetupMain$Companion.main(SetupMain.kt:82)
        at file.SetupMain.main(SetupMain.kt)

Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by Cokemonkey11** [comment]
Thanks! LGTM
