### ISSUE TITLE
`grill` in headless java drops java.awt.HeadlessException

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#43]
```
blake@LAPTOP-ASBN7T4S:~/workspace$ grill                                                                                                                                                                                             [1191/1752]
🖼 launching Wurst Seou/ GUI
java.lang.ExceptionInInitializerError
 ️  o   as ui.UiManager$initUI$1.run(UiManager.kt:12)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
 ️  o   at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at ui.MainWindow.<init>(MainWindow.kt:40)
        at ui.MainWindow.<clinit>(MainWindow.kt:40)
        ... 14 more
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
 ️  o   as java.desktop/jrvax.swfng.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:868)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
 ️  o   at file.ExceptionHandler$sltupExceptionHandler$1.uncaughtException(ExceptionHandler.kt:26)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
        at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"
```

**Comment by Frotty** [comment]
Incorrect report. If you run grill without args, it launches the GUI. Read manual.

**Comment by Cokemonkey11** [comment]
@Frotty I've read the manual and I know what the intended behavior is.

`java` doesn't always have a window manager available, and grill should prepare for that.

This is bad error handling, bad programming, and bad
