### ISSUE TITLE
Jackson deser error on grill install

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#57]
First time I've seen this - happened while iterating on an old jurst project:

```
$ grill install
🔥 Grill warming up..
Custom WurstScript installation detected.
🔥 Ready. Version: <1.3.4.1-jenkins-WurstSetup-152>
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)
 at [Source: (String)"// Place your settings in this file to overwrite default and user settings.
{
    "editor.rulers": [80],
    "wurst.wurstJar": "C:\\Users\\Blake\\workspace2\\WurstScript\\Wurstpack\\wurstscript\\wurstscript.jar",
    "wurst.wc3path": "C:/Program Files (x86)/Warcraft III/"
}"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1922)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComment(ReaderBasedJsonParser.java:2471)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd2(ReaderBasedJsonParser.java:2446)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2397)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:677)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4620)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
        at config.WurstProjectConfig.modifySettingsJson(WurstProjectConfig.kt:167)
        at config.WurstProjectConfig.setConfigValues(WurstProjectConfig.kt:152)
        at config.WurstProjectConfig.setupVSCode(WurstProjectConfig.kt:147)
        at config.WurstProjectConfig.handleUpdate(WurstProjectConfig.kt:183)
        at file.SetupApp.handleUpdateProject(SetupApp.kt:255)
        at file.SetupApp.handleRunArgs(SetupApp.kt:78)
        at file.SetupApp.handleCMD(SetupApp.kt:58)
        at file.SetupApp.handleArgs(SetupApp.kt:41)
        at file.SetupMain.doMain(SetupMain.kt:40)
        at file.SetupMain$Companion.main(SetupMain.kt:84)
        at file.SetupMain.main(SetupMain.kt)
```

**Comment by Cokemonkey11** [comment]
The file was `.vscode/settings.json`:

```
// Place your settings in this file to overwrite default and user settings.
{
    "editor.rulers": [80],
    "wurst.wurstJar": "C:\\Users\\Blake\\workspace2\\WurstScript\\Wurstpack\\wurstscript\\wurstscript.jar",
    "wurst.wc3path": "C:/Program Files (x86)/Warcraft III/"
}
```

No idea why grill is trying to read it

**Comment by Frotty** [comment]
invalid json syntax I suppose. grill reads/writes it of course

**Comment by Cokemonkey11** [comment]
@Frotty can we reopen this? I don't think grill should be reading/writing `.vscode/settings.json`!

**Comment by Frotty** [comment]
it should

**Comment by Cokemonkey11** [comment]
@Frotty in that case I think this should be reopened since all vscode projects [have this non-json comment by default](https://github.com/search?q=org%3Amicrosoft+%22%2F%2F+Place+your+settings+in+this+file+to+overwrite+default+and+user+settings.%22&type=code)
