### ISSUE TITLE
Exception occured on startup (some old-ish version)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#6]
```
Please report this crash with the following info:
Version: 1.1.3.1-jenkins-WurstSetup-29
java.lang.ExceptionInInitializerError
	at file.SetupMain.doMain(SetupMain.kt:43)
	at file.SetupMain$Companion.main(SetupMain.kt:53)
	at file.SetupMain.main(SetupMain.kt)
Caused by: us.monoid.json.JSONException: JSONObject["buildsByBranchName"] not found.
	at us.monoid.json.JSONObject.get(JSONObject.java:419)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:74)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.JSONPathQuery.eval(JSONPathQuery.java:42)
	at us.monoid.web.JSONResource.get(JSONResource.java:130)
	at net.ConnectionManager.getJson(ConnectionManager.kt:17)
	at net.ConnectionManager.getLatestCompilerBuild(ConnectionManager.kt:48)
	at global.InstallationManager.verifyInstallation(InstallationManager.kt:41)
	at file.SetupApp.<clinit>(SetupApp.kt:29)
	... 3 more
```

**Comment by Frotty** [comment]
okay? why do you report this?
