### ISSUE TITLE
PrivilegedActionException when trying to extract package

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstSetup#9]
_From @hzj61002963 on March 18, 2018 14:30_

Please report this crash with the following info:
```
Version: 1.1.4.0-jenkins-WurstSetup-54
java.security.PrivilegedActionException: java.util.zip.ZipException: error in opening zip file
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at file.ZipArchiveExtractor.extractArchive(ZipArchiveExtractor.kt:27)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:103)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:19)
	at workers.DownloadWithProgressWorker.done(DownloadWithProgressWorker.kt:56)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	... 9 more

```

_Copied from original issue: wurstscript/WurstScript#630_

**Comment by Frotty** [comment]
This is a setup issue. Moving to correct project.

**Comment by Frotty** [comment]
@hzj61002963 **PrivilegedActionException** looks like the zipfile is in a folder that doesn't allow extraction. This doesn't look like it has anything to do with your location, but with your machine setup.
Check if you have necessary read/write privileges inside your user folder `~/`

Which OS are you using?

**Comment by Frotty** [comment]
Did it work for you now?

**Comment by lhing17** [comment]
I'm encountering the exact same problem. It seems that the downloaded zip file is incomplete, it cannot be opened by other upzipping tools. Is there any other way to download the zip file?

**Comment by lhing17** [comment]
By the way, I'm using Windows 7 and I use the administrator account, so I have necessary read/write privileges inside my user folder.

**Comment by lhing17** [comment]
When I ran the WurstSetup.jar using java -jar, I got a message "couldn't contact google: Stream closed" but the program continued to work.

**Comment by lhing17** [comment]
It works after I tried again...

**Comment by Frotty** [comment]
Please don't spam posts, Edit your original one.
This seems to be some Chinese location related problem.
Unless you have more precise info I don't know how to fix it.

**Comment by lhing17** [comment]
It seems to be caused by a network interrupt while downloading. Maybe it's better to directly start installing WurstScript if the zip file exists (without download again), then we can download the zip file separately.

**Comment by peq** [comment]
Hm, could be a problem with the https://letsencrypt.org/ certificate we are using. It could be that the corresponding root certificate is not installed with your Java version or something like that. The fallback from https to http might not be working as intended in this case.

You can always download the Compiler from http://peeeq.de/hudson/job/Wurst/lastSuccessfulBuild/artifact/downloads/ and extract it manually. The old manual installation guide (https://github.com/wurstscript/wurst4vscode/tree/e607c7be53427b9444332621ca0a34f6670445c7#manual-configuration) should still work. Maybe we have to add it to the manual again, if we cannot fix the Setup tool.
